### ISSUE TITLE
private-only not working?

### ISSUE THREAD

**Issue by job** [rucarrol/PeerFinder#2]
i was expecting different results from this query:

```
hanna:tmp job$ python peerfinder.py --private-only --myasn 2914 --peerasn 6453
Fetching PeeringDB info for 2914
Fetching PeeringDB info for 6453
Didnt find any common IX
```

**Comment by rucarrol** [comment]
Thank you for the bug report! I've added commit  [733501f457a1f0627c018e422bc63ba83056e826](https://github.com/rucarrol/PeerFinder/commit/733501f457a1f0627c018e422bc63ba83056e826), which should fix the logic short term.

Medium term, I'll refactor next week to make the code more readable/more defensive.

**Comment by rucarrol** [comment]
Ok, code refactored and seems to be working now. Please let me know if/when you find more breakage.
