### ISSUE TITLE
Same IP shown, when multiple addresses available

### ISSUE THREAD

**Issue by lukastribus** [rucarrol/PeerFinder#6]
When a peer has multiple IP addresses, only the latest IP address is shown multiple times.

Just look at the example in README.md, the same IP is shown multiple times, both in v4 and v6.

**Comment by rucarrol** [comment]
That's for reporting this - I'm working on a fix.

**Comment by rucarrol** [comment]
PR #7 should fix this issue.

**Comment by lukastribus** [comment]
Thanks!
